services:
  certenrollweb:
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USER_WEBDAV=${USER_WEBDAV:-svc_certenrollweb-webdav}
      - PASS_WEBDAV=${PASS_WEBDAV:-securepassword123}
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
    ports:
      - "10080:80"
      - "18080:8080" # WebDAV Port
    volumes:
      - cert-data:/var/www/CertEnroll
    restart: unless-stopped

volumes:
  cert-data:
